name: essentials
description: a simplified essentials for 1.8
main: net.anthonyloukinas.essentials.Main
version: 1.0
commands:
    heal:
        description: Heal a player or yourself!
    chickenstorm:
        description: Start a chickenstorm around your location!
    teleport:
        description: Teleport to another player!
    creative:
        description: Change gamemode to creative
    survival:
        description: Change gamemode to survival